# **Forecasting**

## Import Libraries and Dependencies

In [1]:
#Import your libraries and dependencies
import os
import pandas as pd
import alpaca_trade_api as tradeapi
import numpy as np
from MCForecastTools import MCSimulation


%matplotlib inline

## Import Stock Portfolio Data

In [2]:
total_portfolio = pd.read_csv('../../Resources/Stock_Portfolio_Prices.csv', index_col = 'Date', parse_dates = True, infer_datetime_format = True)

total_portfolio.tail(10)

,AAPL,FB,NVDA,PYPL,SHOP,SQ,TDOC,TSLA,TWTR,Z
Date,,,,,,,,,,
2021-05-21,125.430000,316.230011,599.669983,250.690002,1224.119995,200.009995,140.520004,580.880005,54.450001,109.830002
2021-05-24,127.099998,324.630005,624.479980,257.170013,1261.430054,210.949997,142.330002,606.440002,57.060001,112.930000
2021-05-25,126.900002,327.790009,625.909973,258.649994,1240.000000,216.199997,144.460007,604.690002,57.000000,112.550003
2021-05-26,126.849998,327.660004,628.000000,261.369995,1238.829956,222.339996,148.320007,619.130005,57.849998,114.489998
2021-05-27,125.279999,332.750000,619.520020,259.470001,1240.839966,220.899994,149.000000,630.849976,58.080002,115.349998
2021-05-28,124.610001,328.730011,649.780029,260.019989,1242.869995,222.520004,150.580002,625.219971,58.000000,117.320000
2021-06-01,124.279999,329.130005,650.580017,259.269989,1251.560059,221.949997,152.360001,623.900024,57.439999,113.559998
2021-06-02,125.059998,329.149994,671.130005,262.170013,1229.589966,220.410004,152.740005,605.119995,57.160000,111.730003
2021-06-03,123.540001,326.040009,678.789978,257.790009,1199.000000,211.429993,146.589996,572.840027,57.009998,108.430000
2021-06-04,125.889999,330.350006,703.130005,263.040009,1205.739990,213.690002,146.570007,599.049988,59.000000,108.800003